# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: task-generator

custom:
  stage: ${opt:stage, self:provider.stage}
  environment:
    DESCRIPTION:
      production: "Production demo - DO NOT DELETE"
      staging: "Staging demo - DO NOT DELETE"

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs14.x
  stage: staging
  memorySize: 1024
  timeout: 30
  environment:
    'ROOKOUT_TOKEN': ${opt:token}
    'ROOKOUT_CONTROLLER_HOST': ${opt:agenthost}
    'ROOKOUT_ROOK_TAGS': 'tasks-multi-infra'
    'ROOKOUT_LABELS': 'app:tasks-multi-infra,env:${self:custom.stage},type:serverless'
    'ROOKOUT_DEBUG': 1
    'ROOKOUT_REMOTE_ORIGIN': 'https://github.com/Rookout/lambda-node-task-generator.git'
    'ROOKOUT_COMMIT': 'master'

package:
  excludeDevDependencies: true

# The `functions` block defines what code to deploy
functions:
  generateTask:
    description: ${self:custom.environment.DESCRIPTION.${self:custom.stage}}
    tags:
      env: ${self:custom.stage}
    handler: task_generator.handler
    events:
      - http:
          path: task
          method: get
          cors: true
