version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules

  deploy-staging:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
      - run:
          name: Deploy application to staging
          command: sls deploy --stage staging --token ${STAGING_DEMO_ROOKOUT_TOKEN} --agenthost staging.cloud.agent.rookout.com

  deploy-production:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
            
      - run:
          name: Deploy application to production
          command: sls deploy --stage production --token ${DEMO_ROOKOUT_TOKEN} --agenthost cloud.agent.rookout.com



workflows:
  version: 2
  build-and-deploy:
    jobs:
      - hold-for-approval:
         type: approval
         requires:
             - build    
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: build-on-branch-deploy-on-staging
      - deploy-production:
          requires:
            - build
            - deploy-staging
            - hold-for-approval
          filters:
            branches:
              only: build-on-branch-deploy-on-staging              